name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: npm install

      - name: Test
        run: npm test

      - name: Package
        run: npm run package

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: startpage.zip
          path: dist/startpage.zip

      - name: Submit coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
          COVERALLS_GIT_BRANCH: "${{ github.ref }}"
        run: npm run coveralls

      - name: Deploy demo
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build
