name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: npm install

      - name: Test
        run: npm test

      - name: Package
        run: npm run package

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: startpage.zip
          path: dist/startpage.zip

      - name: SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Submit coverage to Coveralls
        continue-on-error: true
        uses: coverallsapp/github-action@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy demo
        continue-on-error: true
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build
