name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: make build HOST_UID=0 HOST_GID=0

      - name: Test
        run: make test

      - name: Package
        run: make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: startpage.zip
          path: dist/startpage.zip

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Deploy Demo
        continue-on-error: true
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
