name: Pull Request CI

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: make build HOST_UID=0 HOST_GID=0

      - name: Test
        run: make test

      - name: Package
        run: make package
