name: Screenshot

on:
  push:
    branches:
      - master

jobs:
  build:
    continue-on-error: true
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: make build HOST_UID=0 HOST_GID=0

      - name: Start
        run: |
          make start HOST_UID=0 HOST_GID=0
          sleep 10

      - name: Capture Screenshot
        id: newtab
        uses: swinton/screenshot-website@v1.x
        with:
          source: http://localhost:12598/
          destination: newtab.png
          full-page: true
          width: 1200

      - name: Prepare
        run: |
          mkdir screenshots
          cp ${{steps.newtab.outputs.path}} screenshots/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: screenshots
          folder: screenshots
